// tslint:disable
/**
 * Backend API
 * API Documentation for Backend Project
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    OAuthRequest,
    OAuthRequestFromJSON,
    OAuthRequestToJSON,
    OAuthResponse,
    OAuthResponseFromJSON,
    OAuthResponseToJSON,
} from '../models';

export interface OauthTokenPostRequest {
    oAuthRequest: OAuthRequest;
}

/**
 * no description
 */
export class OauthApi extends runtime.BaseAPI {

    /**
     */
    async oauthTokenPostRaw(requestParameters: OauthTokenPostRequest): Promise<runtime.ApiResponse<OAuthResponse>> {
        if (requestParameters.oAuthRequest === null || requestParameters.oAuthRequest === undefined) {
            throw new runtime.RequiredError('oAuthRequest','Required parameter requestParameters.oAuthRequest was null or undefined when calling oauthTokenPost.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/oauth/token`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: OAuthRequestToJSON(requestParameters.oAuthRequest),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => OAuthResponseFromJSON(jsonValue));
    }

   /**
    */
    async oauthTokenPost(requestParameters: OauthTokenPostRequest): Promise<OAuthResponse> {
        const response = await this.oauthTokenPostRaw(requestParameters);
        return await response.value();
    }

}
