/*
 * Copyright (C) Christian Ascone - All Rights Reserved
 *
 * @project    react-native-expo-template.nosync
 * @file       config-app.ts
 * @author     Christian Ascone
 * @date       10/10/19 2:40 PM
 */

import fs = require('fs');

require('dotenv').config();

fs.readFile('./app.json.example', 'utf8', (err, data) => {
    if (err) {
        console.error(err);
        return
    }
    let targetPath = './app.json';
    let androidGoogleApiKey = process.env.ANDROID_GOOGLE_API_KEY;
    let iosGoogleApiKey = process.env.IOS_GOOGLE_API_KEY;
    data = data.replace('<ANDROID_GOOGLE_API_KEY>', androidGoogleApiKey);
    data = data.replace('<IOS_GOOGLE_API_KEY>', iosGoogleApiKey);
    data = data.replace('<WARNING>', '// THIS FILE IS AUTOGENERATED. EDIT app.json.example AND RUN AGAIN `yarn run setup-app` TO UPDATE THIS FILE.');

    fs.writeFile(targetPath, data, function (err) {
        if (err) {
            console.log(err);
        }
    });
});

